name: react-js-build


on:
  push:
    branches:
      - dev


jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      
      - uses: actions/checkout@v2
      - name: Testing app
        run: |
          yarn install
          yarn test a
    
  build:
    runs-on: ubuntu-latest
    needs: [install-and-test]
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install

      - uses: actions/checkout@v2
      - name: Build App
        run: |
          yarn install
          yarn build
  
  upload: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/release/
